name: Build iOS Dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: true

      - name: Download iOS SDKs
        run: |
          # Xóa thư mục sdks cũ nếu có để tránh lỗi exit code 128
          rm -rf theos/sdks
          # Clone bộ SDK mới về
          git clone https://github.com/theos/sdks.git theos/sdks

      - name: Install ldid
        run: |
          # Cài đặt công cụ ldid để cấp phép (sign) cho file dylib
          brew install ldid

      - name: Build Tweak
        run: |
          # Fix lỗi Exit code 128 của Git khi đọc version
          git config --global --add safe.directory '*'
          
          # Tự động tạo file MenuSupport.plist để sửa lỗi "missing a filter property list"
          echo '{ Filter = { Bundles = ( "com.apple.UIKit" ); }; }' > MenuSupport.plist
          
          # Thiết lập môi trường Theos và tiến hành Build
          export THEOS=${{ github.workspace }}/theos
          make package

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v5
        with:
          name: MenuSupport-Dylib
          path: .theos/obj/debug/*.dylib
