name: Build iOS Dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Setup Theos
        uses: actions/checkout@v5
        with:
          repository: theos/theos
          path: theos
          submodules: true

      - name: Download iOS SDKs
        run: |
          git clone https://github.com/theos/sdks.git theos/sdks

      - name: Build Tweak
        run: |
          # Fix lỗi Exit code 128 của Git
          git config --global --add safe.directory '*'
          
          # Thiết lập Theos và Build
          export THEOS=${{ github.workspace }}/theos
          make package

      - name: Upload Dylib Artifact
        uses: actions/upload-artifact@v5
        with:
          name: MenuSupport-Dylib
          path: .theos/obj/debug/*.dylib
